// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: KSqBdMGJVdcCT3NarXWvP
// Component: er1DyUSXNhrfZ
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_copy_of_starter_blog.css"; // plasmic-import: KSqBdMGJVdcCT3NarXWvP/projectcss
import "./PlasmicPostHeader.css"; // plasmic-import: er1DyUSXNhrfZ/css

export type PlasmicPostHeader__VariantMembers = {};
export type PlasmicPostHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicPostHeader__VariantsArgs;
export const PlasmicPostHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicPostHeader__ArgsType = {
  postTitle?: React.ReactNode;
  date?: React.ReactNode;
  blogTitle?: React.ReactNode;
};
type ArgPropType = keyof PlasmicPostHeader__ArgsType;
export const PlasmicPostHeader__ArgProps = new Array<ArgPropType>(
  "postTitle",
  "date",
  "blogTitle"
);

export type PlasmicPostHeader__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a">;
};

export interface DefaultPostHeaderProps {
  postTitle?: React.ReactNode;
  date?: React.ReactNode;
  blogTitle?: React.ReactNode;
  className?: string;
}

function PlasmicPostHeader__RenderFunc(props: {
  variants: PlasmicPostHeader__VariantsArgs;
  args: PlasmicPostHeader__ArgsType;
  overrides: PlasmicPostHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_KSqBdMGJVdcCT3NarXWvP",
        "PostHeader__root__hxGu"
      )}
    >
      <a
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__a",
          "PostHeader__link__mszE3"
        )}
        href={"/" as const}
      >
        <p.PlasmicSlot
          defaultContents={"Plasmic Starter Blog"}
          value={args.blogTitle}
          className={classNames("PostHeader__slotBlogTitle__du5Cb")}
        />
      </a>

      <p.PlasmicSlot
        defaultContents={"Hello world"}
        value={args.postTitle}
        className={classNames("PostHeader__slotPostTitle__ernjO")}
      />
      <p.PlasmicSlot
        defaultContents={"January 1, 2020"}
        value={args.date}
        className={classNames("PostHeader__slotDate__vfdp9")}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPostHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<
  T extends NodeNameType
> = // Explicitly specify variants, args, and overrides as objects
{
  variants?: PlasmicPostHeader__VariantsArgs;
  args?: PlasmicPostHeader__ArgsType;
  overrides?: NodeOverridesType<T>;
} & // Specify variants directly as props
Omit<PlasmicPostHeader__VariantsArgs, ReservedPropsType> &
  // Specify args directly as props
  Omit<PlasmicPostHeader__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;
function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPostHeader__ArgProps,
      internalVariantPropNames: PlasmicPostHeader__VariantProps,
    });

    return PlasmicPostHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPostHeader";
  } else {
    func.displayName = `PlasmicPostHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicPostHeader = Object.assign(
  // Top-level PlasmicPostHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicPostHeader
    internalVariantProps: PlasmicPostHeader__VariantProps,
    internalArgProps: PlasmicPostHeader__ArgProps,
  }
);

export default PlasmicPostHeader;
/* prettier-ignore-end */
